### PR TITLE
Simplify encoding/decoding API for files

### PR DESCRIPTION
**Pull request by sirMackk**
This is the first shot at simplifying the API as described in #1.

This PR is a WIP.

@prologic, when you have time, can you check out this version of the API and let me know if it would make your life easier? I've mostly stuck with the what was described in the ticket, just tweaked it to quickly get some tests to pass. Mainly wondering if the `Encode`, `Open`, and `Decode` functions have the right inputs/outputs that you expected. Thanks!

### CODE REVIEW

**Comment by prologic** [comment]
This looks good to me.

Q: Are the `partityWriters` passed to the `Encode()` function the result of "sharding + parity" of the input file?

**Comment by sirMackk** [comment]
@prologic, the parityWriters are where to write the parity outputs (most likely *os.Files, but could be other streams). Eg. given `f` data file, create `len(parityWriters)` parity shards.

Also, happy new year :).

**Comment by prologic** [comment]
> @prologic, the parityWriters are where to write the parity outputs (most likely *os.Files, but could be other streams). Eg. given `f` data file, create `len(parityWriters)` parity shards.

Is this functionally equivilent to https://github.com/prologic/reedlib/blob/master/cmd/reed-encode/main.go ?

> Also, happy new year :).

Happy New Year! 🎉

**Comment by prologic** [comment]
> > @prologic, the parityWriters are where to write the parity outputs (most likely *os.Files, but could be other streams). Eg. given `f` data file, create `len(parityWriters)` parity shards.
> 
> Is this functionally equivilent to https://github.com/prologic/reedlib/blob/master/cmd/reed-encode/main.go ?

With hashing and a `Metadata` object

**Comment by sirMackk** [comment]
> Is this functionally equivilent to https://github.com/prologic/reedlib/blob/master/cmd/reed-encode/main.go ?

It's a little different: instead of outputting separate data and parity shards, the code here only outputs the parity shards and metadata object, leaving what to do with the data and metadata to the users of the library.

**Pull request merged**
